name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.12.4

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Restore dependencies
      id: deps-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      if: steps.deps-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Cache dependencies
      if: steps.deps-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ steps.deps-cache.outputs.cache-primary-key }}
